### ISSUE TITLE
Installer requires sudo

### ISSUE THREAD

**Issue by parkerault** [MISoftware/IconDrop#1]
Is there any particular reason to require root access for the installer? It appears that there aren't any install scripts and the only files installed are in IconDrop.app. Random utilities that I downloaded off the internet asking for root access to install makes me extremely wary, and distributing as a standalone mac app would be much less suspicious.

**Comment by midiway** [comment]
Yeahh, no need for root access. It is just that Visual Studio generates the .pkg this way.

Do you know how to disable it?

**Comment by parkerault** [comment]
I don't but you can just take the bundled .app out of the pkg and distribute it as a zip file. This is how most third party mac software is distributed.

**Comment by midiway** [comment]
The app is now distributed as a .app, no more .pkg, so no more sudo needed
